import { defineIntegration, createRestHandler } from '@weldable/integration-core'

const rest = createRestHandler()

export default defineIntegration({
  id: 'google_tasks',
  name: 'Google Tasks',
  description: 'Create, manage, and complete tasks and to-do lists in Google Tasks.',
  icon: 'google-tasks',
  version: 1,
  baseUrl: 'https://tasks.googleapis.com/tasks/v1',
  auth: {
    type: 'oauth2',
    test: async (_, ctx) => ctx.http.get('/users/@me/lists', { query: { maxResults: '1' } }).then(r => r.data as Record<string, unknown>),
  },
  nangoScopes: 'openid,email,https://www.googleapis.com/auth/tasks',
  nangoCredentialEnvPrefix: 'GOOGLE',
  exampleUsage: "Show me my to-do list",
  actions: [
    // ── Task Lists ────────────────────────────────────────────
    {
      actionId: 'list_tasklists',
      name: 'List task lists',
      description: 'List all task lists in the Google Tasks account.',
      intents: [
        'show my task lists',
        'what to-do lists do I have',
        'list my google task lists',
        'see all my task lists',
        'what task lists are there',
      ],
      inputFields: [
        {
          name: 'maxResults',
          type: 'number',
          required: false,
          description: 'Maximum number of task lists to return.',
          default: 100,
        },
        {
          name: 'pageToken',
          type: 'string',
          required: false,
          description: 'Token for the next page of results.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of task lists, each with id, title, and updated timestamp.' },
        { name: 'nextPageToken', type: 'string', description: 'Token for the next page of results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/users/@me/lists',
        paramMapping: { maxResults: 'query', pageToken: 'query' },
      }),
    },
    {
      actionId: 'get_tasklist',
      name: 'Get task list',
      description: 'Get details for a specific task list.',
      intents: [
        'get task list details',
        'look up a task list',
        'see info about a task list',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: true,
          description: 'The ID of the task list.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Task list ID.' },
        { name: 'title', type: 'string', description: 'Task list title.' },
        { name: 'updated', type: 'string', description: 'Last updated timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'GET',
        path: '/users/@me/lists/{tasklist}',
        paramMapping: { tasklist: 'path' },
      }),
    },
    {
      actionId: 'create_tasklist',
      name: 'Create task list',
      description: 'Create a new task list.',
      intents: [
        'create a new task list',
        'add a new task list',
        'make a new task list',
        'set up a new task list',
        'create a task category',
      ],
      inputFields: [
        {
          name: 'title',
          type: 'string',
          required: true,
          description: 'Title of the new task list.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'New task list ID.' },
        { name: 'title', type: 'string', description: 'Task list title.' },
        { name: 'updated', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/users/@me/lists',
        paramMapping: { title: 'body' },
      }),
    },
    // ── Tasks ─────────────────────────────────────────────────
    {
      actionId: 'list_tasks',
      name: 'List tasks',
      description: 'List tasks in a task list, with optional filtering by due date, completion status, and more.',
      intents: [
        'show my tasks',
        'what do I need to do',
        'list my to-dos',
        'see my task list',
        'show my pending tasks',
        'what tasks are due this week',
        'show completed tasks',
        'see all my tasks',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: false,
          description: 'Task list ID. Defaults to the primary task list.',
          default: '@default',
        },
        {
          name: 'maxResults',
          type: 'number',
          required: false,
          description: 'Maximum number of tasks to return.',
          default: 100,
        },
        {
          name: 'dueMin',
          type: 'string',
          required: false,
          description: 'Lower bound for task due date (RFC3339).',
        },
        {
          name: 'dueMax',
          type: 'string',
          required: false,
          description: 'Upper bound for task due date (RFC3339).',
        },
        {
          name: 'showCompleted',
          type: 'boolean',
          required: false,
          description: 'Whether to include completed tasks.',
          default: false,
        },
        {
          name: 'showHidden',
          type: 'boolean',
          required: false,
          description: 'Whether to include hidden tasks.',
          default: false,
        },
        {
          name: 'showDeleted',
          type: 'boolean',
          required: false,
          description: 'Whether to include deleted tasks.',
          default: false,
        },
        {
          name: 'completedMin',
          type: 'string',
          required: false,
          description: 'Lower bound for task completion date (RFC3339).',
        },
        {
          name: 'completedMax',
          type: 'string',
          required: false,
          description: 'Upper bound for task completion date (RFC3339).',
        },
        {
          name: 'pageToken',
          type: 'string',
          required: false,
          description: 'Token for the next page of results.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of tasks, each with id, title, status, due, and notes.' },
        { name: 'nextPageToken', type: 'string', description: 'Token for the next page of results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/lists/{tasklist}/tasks',
        paramMapping: {
          tasklist: 'path',
          maxResults: 'query',
          dueMin: 'query',
          dueMax: 'query',
          showCompleted: 'query',
          showHidden: 'query',
          showDeleted: 'query',
          completedMin: 'query',
          completedMax: 'query',
          pageToken: 'query',
        },
      }),
    },
    {
      actionId: 'get_task',
      name: 'Get task',
      description: 'Get details for a specific task.',
      intents: [
        'get task details',
        'look up a task',
        'see a specific task',
        'read a task',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: false,
          description: 'Task list ID.',
          default: '@default',
        },
        {
          name: 'task',
          type: 'string',
          required: true,
          description: 'The ID of the task.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Task ID.' },
        { name: 'title', type: 'string', description: 'Task title.' },
        { name: 'status', type: 'string', description: 'Task status: needsAction or completed.' },
        { name: 'due', type: 'string', description: 'Due date (ISO 8601).' },
        { name: 'notes', type: 'string', description: 'Task notes.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/lists/{tasklist}/tasks/{task}',
        paramMapping: { tasklist: 'path', task: 'path' },
      }),
    },
    {
      actionId: 'create_task',
      name: 'Create task',
      description: 'Create a new to-do item or task in a task list. Optionally create it as a subtask by specifying a parent task.',
      intents: [
        'add a task',
        'create a to-do',
        'add something to my task list',
        'create a new task',
        'add a reminder',
        'put a task on my list',
        'add a to-do item',
        'make a new task',
        'add a subtask',
        'create a subtask under',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: false,
          description: 'Task list ID to add the task to.',
          default: '@default',
        },
        {
          name: 'title',
          type: 'string',
          required: true,
          description: 'Title of the task.',
        },
        {
          name: 'notes',
          type: 'string',
          required: false,
          description: 'Notes or description for the task.',
        },
        {
          name: 'due',
          type: 'string',
          required: false,
          description: 'Due date (RFC3339 timestamp with time set to midnight, e.g. "2024-03-15T00:00:00.000Z").',
        },
        {
          name: 'status',
          type: 'string',
          required: false,
          description: 'Status: "needsAction" (default) or "completed".',
          default: 'needsAction',
        },
        {
          name: 'parent',
          type: 'string',
          required: false,
          description: 'Parent task ID. If set, the new task is created as a subtask of this parent.',
        },
        {
          name: 'previous',
          type: 'string',
          required: false,
          description: 'Previous sibling task ID. The new task is positioned after this task in the list.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Task ID.' },
        { name: 'title', type: 'string', description: 'Task title.' },
        { name: 'status', type: 'string', description: 'Task status: needsAction or completed.' },
        { name: 'due', type: 'string', description: 'Due date (ISO 8601).' },
        { name: 'updated', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/lists/{tasklist}/tasks',
        paramMapping: { tasklist: 'path', title: 'body', notes: 'body', due: 'body', status: 'body', parent: 'query', previous: 'query' },
      }),
    },
    {
      actionId: 'update_task',
      name: 'Update task',
      description: 'Update an existing task, such as marking it complete, changing the title, or updating the due date.',
      intents: [
        'mark a task as done',
        'complete a task',
        'check off a task',
        'update a task',
        'change a task due date',
        'rename a task',
        'mark a to-do as complete',
        'finish a task',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: false,
          description: 'Task list ID.',
          default: '@default',
        },
        {
          name: 'task',
          type: 'string',
          required: true,
          description: 'The ID of the task to update.',
        },
        {
          name: 'title',
          type: 'string',
          required: false,
          description: 'New title for the task.',
        },
        {
          name: 'notes',
          type: 'string',
          required: false,
          description: 'New notes or description.',
        },
        {
          name: 'due',
          type: 'string',
          required: false,
          description: 'New due date (RFC3339 timestamp).',
        },
        {
          name: 'status',
          type: 'string',
          required: false,
          description: 'New status: "needsAction" or "completed".',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Task ID.' },
        { name: 'title', type: 'string', description: 'Task title.' },
        { name: 'status', type: 'string', description: 'Updated task status: needsAction or completed.' },
        { name: 'due', type: 'string', description: 'Due date (ISO 8601).' },
        { name: 'updated', type: 'string', description: 'Last updated timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'PUT',
        path: '/lists/{tasklist}/tasks/{task}',
        paramMapping: { tasklist: 'path', task: 'path', title: 'body', notes: 'body', due: 'body', status: 'body' },
      }),
    },
    {
      actionId: 'delete_task',
      name: 'Delete task',
      description: 'Permanently delete a task from a task list.',
      intents: [
        'delete a task',
        'remove a to-do',
        'delete a task from my list',
        'get rid of a task',
        'remove a task',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: false,
          description: 'Task list ID.',
          default: '@default',
        },
        {
          name: 'task',
          type: 'string',
          required: true,
          description: 'The ID of the task to delete.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the task was deleted successfully.' },
      ],
      execute: rest({
        method: 'DELETE',
        path: '/lists/{tasklist}/tasks/{task}',
        paramMapping: { tasklist: 'path', task: 'path' },
      }),
    },
    {
      actionId: 'move_task',
      name: 'Move task',
      description: 'Move a task to a different position or make it a subtask of another task.',
      intents: [
        'move a task',
        'make a task a subtask',
        'reparent a task',
        'reorder a task',
        'nest a task under another',
      ],
      inputFields: [
        {
          name: 'tasklist',
          type: 'string',
          required: false,
          description: 'Task list ID.',
          default: '@default',
        },
        {
          name: 'task',
          type: 'string',
          required: true,
          description: 'The ID of the task to move.',
        },
        {
          name: 'parent',
          type: 'string',
          required: false,
          description: 'New parent task ID. If set, the task becomes a subtask. Omit or pass empty to move to top level.',
        },
        {
          name: 'previous',
          type: 'string',
          required: false,
          description: 'Task ID of the previous sibling. The task is positioned after this task.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Task ID.' },
        { name: 'title', type: 'string', description: 'Task title.' },
        { name: 'parent', type: 'string', description: 'Parent task ID (if now a subtask).' },
        { name: 'updated', type: 'string', description: 'Last updated timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/lists/{tasklist}/tasks/{task}/move',
        paramMapping: { tasklist: 'path', task: 'path', parent: 'query', previous: 'query' },
      }),
    },
  ],
})
